### PR TITLE
Get rid of the horrendous HighDPI garbage

### PR DESCRIPTION
**Pull request by lexisother**
For the love of God, it's not configurable, and above all, helps nobody.

### CODE REVIEW

**Comment by 20kdc** [comment]
...I'm translating this as "it broke on my system".
The problem is, some systems are high-DPI and will basically force you to deal with it. There's no good solution here. As it is, `FRENYARD_SCALE` allows manual control when it fucks up.

**Comment by lexisother** [comment]
I see, I wasn't aware of `FRENYARD_SCALE`. Thanks for the hint.
As for "it broke on my system", well, I highly doubt it's just a "me problem".
How is it not? Well, I'm sure you've seen this before:
image

**Comment by 20kdc** [comment]
I haven't. But yeah, ow, that looks like pain.
The problem is basically that the DPI mechanisms don't actually offer any way to determine the *correct* scale, only, well, DPI. This makes no sense to me.

**Comment by lexisother** [comment]
Maybe we can continue chatting about the details via Discord (or any other preferred method of communication that isn't PR comments), if you'd like. I'm quite interested in this stuff, if you hadn't noticed.

**Comment by 20kdc** [comment]
Had an idea:
Keep the HighDPI flag on, but read the display height and use that as a reference for how big the scale ought to be.

**Comment by lexisother** [comment]
Sounds like a better idea, yeah. I'll just close this PR and leave that one up to you, as I'm not sure how to implement that myself.

**Comment by 20kdc** [comment]
Go is refusing to build the project here for it's own... reasons
I now have patches which are probably most of the way there in terms of solving the DPI problem

**Comment by 20kdc** [comment]
[0001-Most-of-the-way-there-UNFINISHED-PATCH.patch.txt](https://github.com/dmitmel/CCUpdaterUI/files/7070634/0001-Most-of-the-way-there-UNFINISHED-PATCH.patch.txt)

**Pull request closed without merging**
